Global seed set to 42
Traceback (most recent call last):
  File "/Users/kilianhaefeli/pytorch_lightning_template/train_Points_MLP.py", line 21, in <module>
    trainer = PROJECTTrainer(model_type, problem_type, data_kwargs, dataset_kwargs, model_kwargs, training_kwargs, lightning_kwargs, global_kwargs, resume)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kilianhaefeli/pytorch_lightning_template/project/train.py", line 59, in __init__
    self._init_model()
  File "/Users/kilianhaefeli/pytorch_lightning_template/project/train.py", line 118, in _init_model
    self.net = Net(**self.model_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable